@url_dev=http://localhost:3052/v1/api/

### signup

POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: f1a4d0822489e2c14f909da786167c796fc0842b3ce24f909d4b5dfe538a584460dd7cb4380f3afd7df4ced759e4f66c0de808c31a94eae9e066e3d12986dba3

{
    "name": "SHOP TIPS",
    "email": "shoptipjsDEV_main4@gmail.com",
    "password": "abc123"
}
