@url_dev=http://localhost:3052/v1/api/

### signup

POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: d78f0a1bfc9d1a1463926d88fd326b84dd20ca5a353a2eeb3b01cbd9e46cdb0de83ffde5d4b753e9449c7aa1ddffb90be7e5fa28193272a6a5685903dd092173

{
    "name": "SHOP TIPS",
    "email": "shoptipjs04@gmail.com",
    "password": "abc123"
}